meta_product_name: "SALT"
meta_title: "SALT - Find where the surf is pumping near you"
meta_description: "SALT will find for you the best spots to go surfing from your location, in a specific radius"
meta_image: "salt_background.png" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards
